[theme]
primaryColor = "#3B82F6"
backgroundColor = "#F0F5FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 50
headless = true

[browser]
gatherUsageStats = false
